#!/bin/bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

payload=$(mktemp $TMPDIR/concourse-gcs-rsync-resource-request.XXXXXX)

cat > $payload <&0

bucket=$(jq -r '.source.bucket' < $payload)
remote_path=$(jq -r '.source.remote_path' < $payload)
json_key=$(jq -r '.source.json_key' < $payload)

function check_version() {
  echo "${json_key}" > $TMPDIR/google_service_account.json
  gcloud auth activate-service-account --key-file="$TMPDIR/google_service_account.json"
  gsutil ls -l "gs://$bucket/$remote_path/**" &> $TMPDIR/check.log
  cat check.log \
   | grep -v "$(cat $TMPDIR/check.log | tail -n -1)" \
   | awk '{print $1,$2,$3}' \
   | jq  -R -s '. | split("\n") | del(.[] | select(. == "")) | map(split(" ") | {size: .[0], timestamp: .[1], name: .[2]}) | {files: .} | {version: .}'
}

check_version
