#!/usr/bin/env bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

PLATFORM=`uname`
MD5_TOOL="md5sum"
if [ $PLATFORM = "Darwin" ]; then
  MD5_TOOL="md5"
fi

source=$1

if [ -z "$source" ]; then
  echo "usage: $0 <path/to/source>"
  exit 1
fi

cd $source

payload=$(mktemp $TMPDIR/gcs-rsync-resource-request.XXXXXX)

cat > $payload <&0

bucket=$(jq -r '.source.bucket // ""' < $payload)
json_key=$(jq -r '.source.json_key // ""' < $payload)
base_dir=$(jq -r '.params.base_dir // ""' < $payload)
dry_run=$(jq -r '.params.dry_run // ""' < $payload)

if [ -z "${bucket}" ]; then
  echo "invalid payload (missing bucket)"
  exit 1
fi

if [ -z "$json_key" ]; then
  echo "invalid payload (missing json_key)"
  exit 1
fi

if [ -f "${json_key}" ]; then
  cp "${json_key}" "$TMPDIR/google_service_account.json"
else
  echo "${json_key}" > "$TMPDIR/google_service_account.json"
fi
json_key_file="$TMPDIR/google_service_account.json"

if [ -z "${base_dir}" ] || [ ! -d "${base_dir}" ]; then
  echo "invalid payload (missing base_dir)"
  exit 1
fi

if [ $dry_run ]; then
  dry_run="-n"
fi

gcloud auth activate-service-account --key-file="${json_key_file}" --no-user-output-enabled

listing=$(mktemp $TMPDIR/gcs-rsync-resource-listing.XXXXXX)
metadata_path=$(mktemp $TMPDIR/gcs-rsync-resource-metadata.XXXXXX)

pushd "${base_dir}"
  gsutil -m rsync -d -r ${dry_run} . "gs://${bucket}"

  gsutil ls -l "gs://${bucket}/**" | grep -v 'TOTAL' &> $listing
  IFS=$'\n'
  for file in $(cat $listing)
  do
    echo $file "$(gsutil hash $(echo $file | awk '{print $3}') | grep md5 | awk '{print $3}')" &>> $metadata_path
  done
  unset IFS

  metadata=$(cat $metadata_path \
    | awk '{print $3,$4}' \
    | jq -R -s '
      try (
        split("\n")[:-1] |
        map([ split(" ")[] | select(. != "") ]) |
        map( { name: .[0], value: .[1] } )
      ) catch empty')

  version=$(cat $metadata_path | $MD5_TOOL | cut -d ' ' -f 1)

popd

echo "{ \"version\": { \"ref\": \"$version\"}, \"metadata\": "$metadata" }" >&3
