#!/bin/bash

set -e -x

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

destination=$1
if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>"
  exit 1
fi
export DESTINATION_DIR=$destination

payload=$(mktemp $TMPDIR/gcs-rsync-resource-request.XXXXXX)
cat > $payload <&0

parse_payload $payload
rsync "." "gs://${BUCKET}/${REMOTE_PATH}"
print_version >&3
